name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          TOKEN=$(az acr login --name imageuploaderregistry --expose-token --output tsv --query accessToken)
          docker login imageuploaderregistry.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin <<< $TOKEN
          docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}
          docker tag my-image-name:${{ github.sha }} imageuploaderregistry.azurecr.io/image:${{ github.sha }}
          docker push imageuploaderregistry.azurecr.io/image:${{ github.sha }}
    # - name: Tag the Docker image
    #   run: docker tag my-image-name:$(date +%s) imageuploaderregistry.azurecr.io/image:$(date +%s)
    # - name: Push the Docker image
    #   run: docker push imageuploaderregistry.azurecr.io/image:$(date +%s)
   
